### ISSUE TITLE
code execution backdoor

### ISSUE THREAD

**Issue by di1l0o** [sakuraio/python-sakuraio#43]
We discovered a malicious backdoor in the project's dependencies, present in the /requirements.txt file. Its malicious backdoor is the request package. Even if the request has been deleted by PyPI, many mirror sites have not completely deleted this package, so it can still be installed. Using pip install request -i http://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com, the request malicious plugin can be successfully installed.

![image](https://user-images.githubusercontent.com/58363074/176867043-1f1fd3f0-df58-47f6-b263-1c8f0a80ee61.png)

Suggestion: remove malicious dependency plugin request in /requirements.txt

**Comment by chibiegg** [comment]
thanks
It's TYPO. I fixed it. #44
