### ISSUE TITLE
get_firmware_update_status

### ISSUE THREAD

**Issue by aso** [sakuraio/python-sakuraio#7]
データシートによると
0x80はアップデート試行中を示し
0x40はエラーフラグとのことなので
```
 "inprogress": (response & 0x80) == 0x80,
 "has_error": (response & 0x40) == 0x40,
 "status": response & 0x3f,
```
とした方が良いのかもしれません。

**Comment by chibiegg** [comment]
すいません、データシート、及び、本ライブラリの両方にミスがありました。

![image](https://cloud.githubusercontent.com/assets/855724/25780047/b2c21192-335c-11e7-98a0-ff5d69ead849.png)

エラーがあるかどうかのビットフィールドが存在しないことを除きデータシート通りです。
データシートは後ほど修正いたします。

ご報告ありがとうございます。
